name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag docker-php
    - run: docker run -d docker-php
